<?php
// This class was automatically generated by build task
// You can change it manually, but it will be overwritten on next build

/**

 * Methods from Symfony2
 * @method TestGuy amHttpAuthenticated($username, $password)
 * @method TestGuy amOnPage($page)
 * @method TestGuy click($link)
 * @method TestGuy see($text)
 * @method TestGuy dontSee($text)
 * @method TestGuy seeLink($text)
 * @method TestGuy dontSeeLink($text)
 * @method TestGuy seeInCurrentUrl($uri)
 * @method TestGuy seeCheckboxIsChecked($checkbox)
 * @method TestGuy dontSeeCheckboxIsChecked($checkbox)
 * @method TestGuy seeInField($field, $value)
 * @method TestGuy dontSeeInField($field, $value)
 * @method TestGuy submitForm($selector, $params)
 * @method TestGuy fillField($field, $value)
 * @method TestGuy selectOption($select, $option)
 * @method TestGuy checkOption($option)
 * @method TestGuy uncheckOption($option)
 * @method TestGuy attachFile($field, $filename)
 * @method TestGuy sendAjaxGetRequest($uri)
 * @method TestGuy sendAjaxPostRequest($uri)
 * 
 * Methods from Filesystem
 * @method TestGuy openFile($filename)
 * @method TestGuy seeInFile($text)
 * @method TestGuy dontSeeInFile($text)
 * @method TestGuy seeFileFound($filename)
 * 
 * Methods from TestHelper
**/


class TestGuy extends \Codeception\AbstractGuy
{


}

