#!/usr/bin/env php
<?php

require_once __DIR__.'/bootstrap.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;

$kernel = new AppKernel('dev', true);

$application = new Application($kernel);
$application->run();
