<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120417155202 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE portfolio_projects ADD ordernum INT NOT NULL");
        $this->addSql("ALTER TABLE portfolio_projects ADD onFrontPage TINYINT( 1 ) NOT NULL");
        $this->addSql("SET @rank:=0;");
        $this->addSql("UPDATE portfolio_projects SET ordernum = @rank:=@rank+1, onFrontPage = 1 ORDER BY date DESC");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        $this->addSql("ALTER TABLE portfolio_categories DROP ordernum");
        $this->addSql("ALTER TABLE portfolio_categories DROP onFrontPage");
    }
}
