<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20110416140512 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE portfolio_projects ADD slug VARCHAR(128) NOT NULL");
        $this->addSql("UPDATE portfolio_projects SET slug = REPLACE(SUBSTRING(url, 8), '.', '-')");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_2019E93C989D9B62 ON portfolio_projects (slug)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE portfolio_projects DROP slug");
        $this->addSql("DROP INDEX UNIQ_2019E93C989D9B62 ON portfolio_projects");
    }
}
