<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120803131008 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE portfolio_project_translations (id INT AUTO_INCREMENT NOT NULL, object_id INT DEFAULT NULL, locale VARCHAR(8) NOT NULL, field VARCHAR(32) NOT NULL, content LONGTEXT DEFAULT NULL, INDEX IDX_FB62E6AF232D562B (object_id), UNIQUE INDEX portfolio_project_lookup_unique_idx (locale, object_id, field), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE portfolio_project_translations ADD CONSTRAINT FK_FB62E6AF232D562B FOREIGN KEY (object_id) REFERENCES portfolio_projects (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE portfolio_projects CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE description description LONGTEXT DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("DROP TABLE portfolio_project_translations");
        $this->addSql("ALTER TABLE portfolio_projects CHANGE name name VARCHAR(255) NOT NULL, CHANGE description description LONGTEXT NOT NULL");
    }
}
