<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20110527223633 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE blog_posts ADD slug VARCHAR(128) NOT NULL");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_78B2F932989D9B62 ON blog_posts (slug)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE blog_posts DROP slug");
        $this->addSql("DROP INDEX UNIQ_78B2F932989D9B62 ON blog_posts");
    }
}
