<?php

namespace Application\PortfolioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    /**
     * Get all projects from this category
     * 
     * @param \Application\PortfolioBundle\Entity\Category $category
     * @return array
     */
    public function getProjectsByCategory(\Application\PortfolioBundle\Entity\Category $category)
    {
        $query = $this->getEntityManager()
                ->createQuery('SELECT p FROM PortfolioBundle:Project p
                    JOIN p.categories c WHERE c.id = ?1 ORDER BY p.date DESC');
        $query->setParameter(1, $category->getId());

        return $query->getResult();
    }

    /**
     * Get all projects
     * 
     * @return array
     */
    public function getAllProjects()
    {
        $query = $this->getEntityManager()
                ->createQuery('SELECT p FROM PortfolioBundle:Project p
                    ORDER BY p.date DESC');
        
        return $query->getResult();
    }
}