#!/usr/bin/env ruby

class ImportDb
  def initialize
    @work_dir       = '/var/www/html/'
    @mysql_host     = 'db'
    @mysql_user     = 'root'
    @mysql_password = 'qwerty'
  end

  def unpack_all_db
    packed_dbs = []
    Dir.entries(@work_dir).select do |f|
      packed_dbs << f if f.include? '.sql.gz'
    end
    packed_dbs.each do |packet_db|
      new_db_name = packet_db.split('.gz')[0]
      `cd #{@work_dir} && zcat #{packet_db} > #{new_db_name}`
      `cd #{@work_dir} && rm #{packet_db}`
    end
  end

  def import_all_db
    dbs = []
    Dir.entries(@work_dir).select do |f|
      dbs << f if f.include? '.sql'
    end
    dbs.each do |db|
      `cd #{@work_dir} && mysql -u#{@mysql_user} -p#{@mysql_password} -h #{@mysql_host} < #{db}`
    end
  end
end

dbs = ImportDb.new
dbs.unpack_all_db
dbs.import_all_db
